name: Format

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ^1.24.2

      - name: Check formatting
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "Please format your code"
            exit 1
          fi
